CREATE TABLE Remisiones (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE,
    ORDEN_DE_T VARCHAR(50),
    FACTURA VARCHAR(50),
    FOLIO VARCHAR(50)
);
CREATE TABLE Productos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    DESCRIPCION TEXT
);
CREATE TABLE Recolecciones (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    REMISION_ID INT,
    PRODUCTO_ID INT,
    CANTIDAD INT,
    PESO DECIMAL(10, 2),
    COSTO DECIMAL(10, 2),
    ESTATUS VARCHAR(20),
    FOREIGN KEY (REMISION_ID) REFERENCES Remisiones(ID),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES Productos(ID)
);
CREATE TABLE Clientes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    RFC VARCHAR(50),
    DIRECCION TEXT
);
CREATE TABLE Ordenes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT,
    FECHA_SOLICITADA DATE,
    FECHA_DE_ENTREGA DATE,
    MATERIAL_A VARCHAR(255),
    FOLIO VARCHAR(50),
    COMENTARIOS TEXT,
    CANTIDAD INT,
    OBRA VARCHAR(255),
    ESTATUS VARCHAR(20),
    ENTREGADA INT,
    RESTANTE INT,
    REMISION VARCHAR(50),
    FOREIGN KEY (CLIENTE_ID) REFERENCES Clientes(ID)
);
